#!/usr/bin/env bash

# Usage: studio clean   
# Summary: Deletes the contents of the build directory.
# Help: studio clean 
#       Deletes the contents of the build directory.

if [ -z $STUDIO_PROJECT_BUILD_PATH ]; then
  echo "STUDIO_PROJECT_BUILD_PATH is not set."
  echo "Please source study area setup script."
  exit 1
else
  if [ ! "X$STUDIO_PROJECT_BUILD_PATH" = "X" ]; then 
    echo "Cleaning build directory."
    echo "rm -rf  $STUDIO_PROJECT_BUILD_PATH/*"
    rm -rf $STUDIO_PROJECT_BUILD_PATH/*
  else
    echo "STUDIO_PROJECT_BUILD_PATH is set but empty."
    echo "Will not rm -rf /* !"
  fi
fi
