#!/usr/bin/env bash

# Usage: studio build <OPTIONAL> SRC_DIR_NAME ... <OPTIONAL> SRC_DIRNAME 
# Summary: studio build is primarily here to build your code. 
#          Behind the scenes most of this is calling cmake, but there's a little more going on than that.
#	   If you pass build specific subdirectories than only those will get built. If you 
#	   are IN a source subdirectory then only that subdirectory will get built. Yes, studio
#	   does still use an out of source build, you just don't have to flip back and forth. 
#          studio with do it for you! 
# Help: the build command
# 	no options here... just call studio build if you want your entire src directory built
#	or call studio build dir1 ... dirN if you want them all built.

echo ""
# =+=+=+=+=+=+=+=+=+=+=+=+=+=+
# =+=+=+=+=+=+=+=+=+=+=+=+=+=+
# += checking for setup run +=
# =+=+=+=+=+=+=+=+=+=+=+=+=+=+
# =+=+=+=+=+=+=+=+=+=+=+=+=+=+

if [ -z $BUILD_PATH ]; then
  echo "Please source setup script"
  exit 1
fi

# =+=+=+=+=+=+=+=+=+=+=+=+=+=+
# =+=+=+=+=+=+=+=+=+=+=+=+=+=+
# += checking for dir paths +=
# =+=+=+=+=+=+=+=+=+=+=+=+=+=+
# =+=+=+=+=+=+=+=+=+=+=+=+=+=+

#some variables I want
in_source=true
working_dir=""
build_dirs="no args"

#checking if args are read in
if [ -z $1 ]; then
  echo ""
  echo ""
  echo "You have not specified to build specific directories..."
  echo "Checking where you are..."
  #checking if not in source
  insrc=`echo $PWD | grep $SRC_PATH`
  if [ -z $insrc ]; then
    echo ""
    echo ""
    echo "You are not in source directory"
    echo "Building everything in /src directory..."
    echo "If you would like to only build a subset of directories inside"
    echo "/src/... then please refer to help pages"
    echo ""
    in_source=false
    working_dir="/home/rbouabid/studio/studio/libexec/src"
    build_dirs="no args"
    #cmake -D IS_IN_SOURCE:BOOL=FALSE -D WORKING_DIR:STRING=$SRC_PATH -D BUILD_DIRS:STRING="no args" /home/rbouabid/studio/studio/libexec/CMakeLists.txt
  else
    echo ""
    echo ""
    echo "You are somewhere inside the source directory and have not specified a specific directory(s) to build..."
    echo "Passing $PWD as the directory to build."
    echo "If you would like to build something else as well, please see the help pages"
    in_source=true
    working_dir="$PWD"
    build_dirs="no args"
    #cmake -D IS_IN_SOURCE:BOOL=TRUE -D WORKING_DIR:STRING=$PWD -D BUILD_DIRS:STRING="no args" /home/rbouabid/studio/studio/libexec/CMakeLists.txt
    ###consider adding cmake lists if they're not present
  fi

else
  # ---------- ----------
  # -- reading in args --
  # ---------- ----------
  temp=""
  for var;
  do
  temp=$temp"$var;"
  done
  dir_list=${temp%;}
  #echo "$dir_list"
  in_source=true
  working_dir="$PWD"
  build_dirs="$dir_list"
  #cmake -D BUILD_DIRS:STRING="$dir_list" /home/rbouabid/studio/studio/libexec/CMakeLists.txt
  # ------  -  - --------
  # -----+  ^  ^  +------
  # ------- ---- --------
fi

if [ "$PWD" != "$BUILD_PATH" ]; then
    cd $BUILD_PATH 
    echo "getting you to build directory..."
fi

export CC=/products/gcc/v4_9_3a/Linux64bit+2.6-2.12/bin/gcc
export CXX=/products/gcc/v4_9_3a/Linux64bit+2.6-2.12/bin/g++
#cmake /home/rbouabid/studio/studio/libexec 
echo "in_source = $in_source"
echo "working_dir = $working_dir"
echo "build_dirs = $build_dirs"
echo "pwd = $PWD"
#some debug stuff

cmake -D IS_IN_SOURCE:BOOL=$in_source -D WORKING_DIR:STRING="$working_dir" -D BUILD_DIRS:STRING="$build_dirs" -B $BUILD_PATH ..
make 











#tears
