#!/usr/bin/env bash
# Usage: studio create-filter <name>
#
# Summary: Writes a skeleton filter plugin and a FHiCL file to src
#
# Help: studio create-filter <name> 
#
#     Calls 'cetskelgen filter <name>',
#     creates an appropriate FHiCL file, 
#     and updates your source directory CMakeLists.txt file to compile
#     and link your plugin library.
#
#     NOTE: If you should decide to remove the generated source file,
#     you must edit the CMakeLists.txt to remove the build commands
#     related to it.
#
#     Can be shortened to 'studio cf <name>'
if [ -z $STUDIO_PROJECT_SRC_PATH ]; then
  echo "Please source the setup script"
  exit 1
fi

#checking for empty call
if [ -z "$1" ]; then
echo "'studio create-filter' requires specification of a plugin name."
echo "Please try 'studio help create-filter'"
exit 2
fi

name="$1"
cd "$STUDIO_PROJECT_SRC_PATH"
echo "$STUDIO_PROJECT_SRC_PATH"
if ( !  cetskelgen filter  "$name" ) ; then 
  echo cetskelgen filter "$name" failed
  exit 2
fi

# ===========
# == cmake ==
# ===========
targ_name="$name"_module
src_name=""$targ_name".cc"
liblist="\${module_lib_list}"

cat << EOT >> $STUDIO_PROJECT_SRC_PATH/CMakeLists.txt

#"$name" lib linking
add_library($targ_name SHARED $src_name)
target_link_libraries($targ_name $liblist)

EOT

touch $STUDIO_PROJECT_SRC_PATH/"$targ_name".fcl
cat << EOT >> $STUDIO_PROJECT_SRC_PATH/"$targ_name".fcl
#"$targ_name".fcl
#bare bones fcl test

physics:{
   filters:{
      f1:{
         module_type: "$name"
      }
   }
   p:["f1"]
}
EOT

echo "To build it now, use 'studio build'."
