#!/usr/bin/env bash
# Usage: studio create-service <name>
#
# Summary: Writes a skeleton service plugin and a FHiCL file to src
#
# Help: studio create-service <name> 
#
#     Calls 'cetskelgen service:--scope,LEGACY <name>',
#     creates an appropriate FHiCL filea
#     and updates your source directory CMakeLists.txt file to compile
#     and link your plugin library.
#
#     NOTE: if you should decide to remove the generated source file,
#     you must edit the CMakeLists.txt to remove the build commands
#     related to it.
#
#     Can be shortened to 'studio cs <name>'
if [ -z $STUDIO_PROJECT_SRC_PATH ]; then
  echo "Please source the setup script"
  exit 1
fi

#checking for empty call
if [ -z "$1" ]; then
echo "'studio create-service' requires specification of a plugin name."
echo "Please try 'studio help create-service'"
exit 2
fi
name="$1"
cd "$STUDIO_PROJECT_SRC_PATH"
echo "$STUDIO_PROJECT_SRC_PATH"

if ( !  cetskelgen service:--scope,LEGACY "$name" ) ; then 
  echo cetskelgen service:--scope,LEGACY "$name" failed
  exit 2
fi

# ===========
# == cmake ==
# ===========
tag="service"
targ_name="$name"_service
src_name=""$targ_name".cc"
liblist="\${service_lib_list}"

cat << EOT >> $STUDIO_PROJECT_SRC_PATH/CMakeLists.txt

#"$name" lib linking
add_library($targ_name SHARED $src_name)
target_link_libraries($targ_name $liblist)

EOT

touch $STUDIO_PROJECT_SRC_PATH/"$targ_name".fcl
cat << EOT >> $STUDIO_PROJECT_SRC_PATH/"$targ_name".fcl
#"$targ_name".fcl
#bare bones fcl test
services: {
  $name: {}
}
EOT

echo "To build it now, use 'studio build'."
